sonar.projectKey=terraform-provider-zohomail
sonar.projectName=terraform-provider-zohomail
sonar.sourceEncoding=UTF-8

sonar.sources=main.go,internal,tools
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/.terraform/**,**/.scannerwork/**,**/docs/**,**/examples/**,**/dist/**,**/bin/**,**/vendor/**,**/terraform-provider-zohomail,tools/tools.go

sonar.go.coverage.reportPaths=coverage.out
